version: '3.7'

services:
  dev-aurora-auth-service:
    build:
      context: ./
      dockerfile: Dockerfile

    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev-aurora-auth-service.entrypoints=web,websecure"
      - "traefik.http.routers.dev-aurora-auth-service.rule=Host(`dev-auth-service.aurora.drenapps.com.br`)"
      - "traefik.http.services.dev-aurora-auth-service.loadbalancer.server.port=3313"
      - "traefik.http.services.dev-aurora-auth-service.loadbalancer.sticky=true"
      - "traefik.http.services.dev-aurora-auth-service.loadbalancer.sticky.cookie.name=token"
      - "traefik.http.services.dev-aurora-auth-service.loadbalancer.sticky.cookie.httpOnly=true"
      - "traefik.http.routers.dev-aurora-auth-service.service=dev-aurora-auth-service"
      - "traefik.http.routers.dev-aurora-auth-service.tls=true"
      - "traefik.http.routers.dev-aurora-auth-service.tls.certresolver=production"
networks:
  default:
    external: true
    name: server_default
